### ISSUE TITLE
关于 vim python 项目 设置虚拟环境路径问题

### ISSUE THREAD

**Issue by ronething** [PegasusWang/linux_config#2]
您好，我本地使用 pipenv 进行 python 虚拟环境的管理

然后每次查看文件会出现这样的问题(pylint (我安装的是python-mode 插件)检查不到模块，因为模块是安装在虚拟环境的，没有安装在系统模块里)

![image](https://user-images.githubusercontent.com/28869910/61990615-5af2c580-b076-11e9-856a-0c6bb2a25f22.png)

请问如何设置 项目的 python 路径 或者说让 pylint 识别到我的项目虚拟环境

尝试安装以下插件貌似无法解决(可能我的姿势不对)

```vim
" pipenv
Plug 'plytophogy/vim-virtualenv'
Plug 'PieterjanMontens/vim-pipenv'
```

还望可以得到您的回复。

**Comment by PegasusWang** [comment]
如果使用的是 python-mode，可以编辑项目根目录下的 .ropeproject/config.py，然后修改     #prefs.add('source_folders', 'src') 去掉注释并加入你虚拟项目的 包的根路径

**Comment by ronething** [comment]
谢谢回复 我说的是 pylint 识别这个模块
发觉之前的那个问题好了
先在 terminal `pipenv shell` 然后 `vim`
![image](https://user-images.githubusercontent.com/28869910/62550096-38458580-b89c-11e9-81c8-07ea762c5694.png)
![image](https://user-images.githubusercontent.com/28869910/62550148-5612ea80-b89c-11e9-8286-064c3bd88bd0.png)
然后就可以看到 pymode 会自动激活这个虚拟环境然后 pylint 也不会报找不到模块的错误了。

现在又有一个问题 <c-]> 跳转的时候提示这个没有 tags 文件问题

![image](https://user-images.githubusercontent.com/28869910/62555353-595ea400-b8a5-11e9-83d0-e2f1c04d6c65.png)


请问有什么方法吗。(看别人是用 ctags 生成 tags 文件)
