### ISSUE TITLE
请问作者是如何在各个文件夹使用 git 备份的？

### ISSUE THREAD

**Issue by roaming-debug** [PegasusWang/linux_config#4]
现在能想到的就只有所有要备份的文件夹放到同一个文件夹中，然后一起 git push 至远程仓库。网上也没有找到完美的解决方案，请问您是怎么做的呢？

**Comment by PegasusWang** [comment]
一般dotfile 就是用一个文件夹 link 进去，用这个文件夹同步就可以。唯一需要注意的就是不要有敏感信息。我一般敏感信息单独一个文件source
