### ISSUE TITLE
我想请问一下“~”这个键放在哪里比较舒服呢

### ISSUE THREAD

**Issue by johnsonkee** [PegasusWang/linux_config#5]
我用的不是hhkb，是一个68键的键盘，然后“~”键原先所在的位置被esc占据了，现在需要FN+esc才能打出来~，因为linux里面经常会用到~键跳转到用户目录，想问一下您把这个键放在了什么位置呢，谢谢！

**Comment by PegasusWang** [comment]
我之前用 hhkb 的时候改到了右下角，现在用的 niz 还是放在右下角的 方向键下 上，我都是用右手肘拍的哈哈
